/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java Library project to get you started.
 * For more details take a look at the Java Libraries chapter in the Gradle
 * user guide available at https://docs.gradle.org/4.9/userguide/java_library_plugin.html
 */

plugins {
    application
    kotlin("jvm") version "1.2.51"
    java
}

application {
    mainClassName="cli.CliKt"
}

repositories {
  mavenCentral()
}

dependencies {
  compile (kotlin("stdlib"))
  compile (kotlin("reflect"))
  testCompile ("junit:junit:4.12")
  compile ("com.github.ajalt:clikt:1.3.0")
  compile ("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
  compile ("com.github.pm-dev:kotlin-janusgraph-ogm:0.13.1")
  compile ("org.apache.tinkerpop:gremlin-core:3.3.")
  compile ("org.apache.tinkerpop:gremlin-driver:3.3.3")
  compile ("org.apache.tinkerpop:hadoop-gremlin:3.3.3")
  compile ("org.apache.tinkerpop:spark-gremlin:3.3.3")
  compile ("org.janusgraph:janusgraph-core:0.2.1")
  compile ("org.janusgraph:janusgraph-cassandra:0.2.1")
  compile ("org.janusgraph:janusgraph-es:0.2.1")
  compile ("org.janusgraph:janusgraph-cql:0.2.1")
  compile ("org.jetbrains.kotlin:kotlin-runtime:1.2.51")
}